name: HeroKu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: juttamejias/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          stack: "container"
          usedocker: true
        env:
          HD_OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          HD_ACCESS_CODE: ""
          HD_OPENAI_PROXY_URL: "https://api.818616.works/v1"
          HD_OPENAI_MODEL_LIST: "-all,gpt-3.5-turbo,gpt-4o,gpt-4o-mini,o3-mini,claude-3-sonnet,claude-3-haiku,claude-3.5-haiku,claude-3.5-sonnet,deepseek-chat,deepseek-reasoner,gemini-1.5-flash"
          
