name: HeroKu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: juttamejias/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          stack: "container"
          usedocker: true
        env:
          HD_OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          HD_ACCESS_CODE: ""
          HD_OPENAI_PROXY_URL: "https://m3.ckit.gold/v1"
          HD_OPENAI_MODEL_LIST: "-all,gpt-4o-mini,gpt-4o-mini-2024-07-18,gpt-3.5-turbo,gpt-3.5-turbo-0125,gpt-4o,gpt-4o-2024-05-13,gpt-4o-2024-08-06,chatgpt-4o-latest,gpt-4-turbo,gpt-4-turbo-2024-04-09,gemini-1.5-pro-latest,claude-3-haiku-20240307,claude-3-5-sonnet-20240620，claude-3-5-sonnet-20241022"
          
