name: HeroKu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: juttamejias/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          stack: "container"
          usedocker: true
        env:
          HD_OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          HD_ACCESS_CODE: ""
          HD_OPENAI_PROXY_URL: "https://m3.ckit.gold/v1"
          HD_OPENAI_MODEL_LIST: "-all,gpt-4o-mini,gpt-3.5-turbo,gpt-4o,claude-3-5-sonnet-20240620,deepseek-r1,gemini-2.0-flash-exp,o3-mini,o1-mini"
          
